### PR TITLE
Add a filter option

### PR DESCRIPTION
**Pull request by aanriot**
@usolved,

Here is a PR adding a filter option.

It allows for example to only display "Virtual SAN" related objects.

There could be a better way to implement a such option, so feel free yo rewrite it of course. :-)

Cheers,

### CODE REVIEW

**Comment by usolved** [comment]
@aanriot Thanks for your PR. It's a nice way to filter on the "$alarm_item{"NAME"}" attribute.

At the moment it's not possible to filter for the "Name" so that is a nice addition. I'm just thinking about adding this option to the existing "-C" parameter so all the filters are at one place and don't having a new parameter. Existing example for object filtering:

```
object = to check a specific object name like a vm name

    		SUBSELECT:
    		name of the vm, ds or esx host. wildcard is allowed like *vmname*
```

The same way we could add a new mode for name select:
```
-C i:name=*Virtual SAN*
```

What do you think about it? Am I missing something or would this also fulfill the needs?

**Comment by aanriot** [comment]
Hello @usolved ,

Indeed, that would be more consistent.

To be honest, I asked myself this question but eventually did a quick and dirty hack in order to solve a production issue.

**Comment by aanriot** [comment]
Handled in https://github.com/usolved/check_usolved_vsphere_alarms/commit/3bab2a870dabf20bbeb0b9914c94221922007f24. Thanks @usolved !

**Comment by aanriot** [comment]
Hello @usolved ,

Have you tested the behaviour of the new mode?

Indeed, I have:

```
$ perl check_usolved_vsphere_alarms.pl -H myhost -U myuser -P mypass
Critical - 7 alarms found. View extended output for more information.
Warning - Virtual SAN Health Alarm 'SCSI Controller on Virtual SAN HCL' on MYCLUSTER (CL: ClusterComputeResource)
Critical - Virtual SAN Health Alarm 'Virtual SAN HCL DB up-to-date' on MYCLUSTER (CL: ClusterComputeResource)
Warning - Virtual SAN Health Alarm 'Stretched cluster health' on MYCLUSTER (CL: ClusterComputeResource)
Warning - Virtual SAN Health Alarm 'Controller Release Support' on MYCLUSTER (CL: ClusterComputeResource)
Critical - Virtual SAN Health Alarm 'Virtual SAN HCL health' on MYCLUSTER (CL: ClusterComputeResource)
Warning - Virtual SAN Health Alarm 'Controller Driver' on MYCLUSTER (CL: ClusterComputeResource)
Warning - Virtual SAN Health Alarm 'Site Latency Health' on MYCLUSTER (CL: ClusterComputeResource)
```

But it returns nothing when using a named filter:

```
$ perl check_usolved_vsphere_alarms.pl -H myhost -U myuser -P mypass -C i:name=Virtual
OK - No alarms found
```

Cheers,

**Comment by usolved** [comment]
You have to use wildcards when you do not search for the exact string expression.
So `i:name=*Virtual*` should work.

**Comment by aanriot** [comment]
@usolved ,

Perfect, thanks.

**Pull request closed without merging**
